# Generated by Django 4.1.5 on 2023-04-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0016_remove_attendance_present_attendance_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Late'), ('E', 'Excused')], max_length=1),
        ),
    ]
